baseURL = "https://sylwit.com"
languageCode = "en-us"
title = "Sylvain Witmeyer, AWS cloud architect consultant"
theme = "sylwit"

googleAnalytics = "UA-138909862-1"


[params]
[params.font]
    name = "Open Sans"
    sizes = [400]

[params.intro]
    title= "Manage. Deploy."

[[params.social]]
url = "https://www.linkedin.com/in/sylvainwitmeyer/"
name = "linkedin"

[[params.social]]
url = "https://medium.com/@sylwit"
name = "medium"

[[params.social]]
url = "https://github.com/sylwit"
name = "github"


[[params.step]]
icon = "fa-sitemap"
title = "Analyze & Research"
description = """
To provide the best solutions, I need a deep understanding of your current reality.
An analysis of your problems, code and infrastructure, combining with the right questions,
will bring up the best solutions. 
"""

[[params.step]]
icon = "fa-file-code"
title = "Architecture & Design"
description = """
It's time to convert my ideas into an actionable plan. How long? How much? Why?
I provide you with different approaches to open up the discussion.
 """

[[params.step]]
icon = "fa-cloud-upload-alt"
title = "Develop & Deploy"
description = """
Because if you want to match the reality I think you must eat your own dog food. For me it means
being hands on in the code, and setting-up CI/CD pipelines.
"""

[[params.step]]
icon = "fa-cogs"
title = "Maintenance & Support"
description = """
I remain available for optimizing and monitoring your application, improving an existing project,
reducing costs of infrastructure, and still being present to help empowering your team.
"""

[[params.reco]]
author = "Jean-Sébastien Coulombe"
company = "National Bank of Canada"
country = "Montreal - Canada"
avatar = "bnc"
description = """
Sylvain a une très grande connaissance technologique de l’environnement AWS et des bonnes pratiques du métier.
Il a permis à l’équipe cybercrimes de mettre en place des patterns et de développer une expertise
sur nos nouvelles technologies, incluant le serverless, les déploiements d’API avec Kubernetes,
la sécurité globale de nos solutions, etc. Sa vision, sa facilité à transmettre ses connaissances
et à rendre les gens autonomes nous ont grandement aidés pour faire évoluer l’ensemble de notre équipe.
"""

[[params.reco]]
author = "Benoît Hamelin"
company = "ElementAI"
country = "Montreal - Canada"
avatar = "elementai"
description = """
Sylvain is a brilliant software developer, efficient against numerous modern platforms. 
Beyond his technical abilities, Sylvain is an foremost thinker and problem solver. 
He speaks his mind clearly, and is a great whiteboard companion. He will see the weakness 
to a solution proposal, and help his team progress towards a solid solution. 
I would work with him again with unmitigated enthusiasm.
"""

[[params.reco]]
author = "Patrice Lelaisant"
company = "Dragonbleu / Venumfight"
country = "Paris - France"
avatar = "venum"
description = """
Nous travaillons avec Sylvain depuis 4 ans pour l'hébergement et l'infogérance de nos sites internet.
Que ce soit pour des services d'investigation liés à des problèmes techniques pointus ou pour des 
demandes de développement, Sylvain a toujours fait preuve d'expertise, de réactivité
et de disponibilité pour mener à bien notre contrat d'infogérance.
Un partenaire de confiance avec lequel vous travaillez main dans la main
"""



# [[params.reco]]
# author = "Jean-François Blouin"
# company = "Scootertuning"
# country = "Quebec - Canada"
# description = """

# """
